config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :members
  has_many :users, through: :members

  validates :name, presence: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates:content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
  has_many :members
  has_many :groups, through: :members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html
      format.json {@new_messages = @messages.where('id > ?', params[:id])}
    end
  end

  def create

    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'}
        format.json
      end
    else
      flash.now[:alert] = 'メッセージを入力してください'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%").where.not(id: current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :"グループ名", class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat_group_name chat-group-form__input', placeholder: 'グループ名を入力してください', autocomplete: "off"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザー名を入力してください", type: "text", autocomplete: "off"}/
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :"チャットメンバー", class: 'chat-group-form__label'
    .chat-group-form__field--right
      #chat-group-users
        .chat-group-user.clearfix
          %input{name: "group[user_ids][]", type: "hidden", value: "#{current_user.id}"}
          %p.chat-group-user__name
            = current_user.name
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      =f.submit class: 'chat-group-form__action-btn'

app/views/groups/_side.html.haml
.side
  .side__menu
    .side__menu__name
      %p
        = current_user.name
    .side__menu__icons
      = link_to new_group_path do
        %span.fa.fa-pencil-square-o
      = link_to edit_user_path(current_user) do
        %span.fa.fa-cog

  .side__group-lists
    - current_user.groups.each do |group|
      = link_to group_messages_path(group) do
        .side__group-lists__group-name
          = group.name
        .side__group-lists__newest-massage
          = group.show_last_message

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: {group: @group}

app/views/groups/index.html.haml
.container
  = render partial: "side"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group}

app/views/layouts/_notifications.html.haml
- if notice
  %p.alert.alert-notice
    = notice
- if alert
  %p.alert.alert-error
    = alert

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_message.html.haml
.main__chat__post{'data-message-id': message.id}
  .main__chat__post__name
    %h3
      = message.user.name
    %p
      = message.created_at.strftime('%Y/%m/%d %H:%M')
  .main__chat__post__message
    - if message.content.present?
      %p
        = message.content
    = image_tag message.image.url, class: 'main__chat__post__message__image' if message.image.present?

app/views/messages/index.html.haml
.container

  = render partial: "/groups/side"

  .main
    .main__header
      .main__header__group-name
        %h1
          = @group.name
      .main__header__member-list
        %p
          - @group.members.each do |member|
            = member.user.name
      .main__header__edit
        = link_to edit_group_path(@group) do
          %p
            Edit

    .main__chat
      = render partial: 'message', collection: @messages
    .main__form
      = form_for [@group, @message], html: {id: 'message_form'} do |f|
        = f.text_field :content, class: 'main__form__message', placeholder: 'type a message', autocomplete: "off"
        = f.label :image, class: 'main__form__icon' do
          %i.fa.fa-image
          = f.file_field :image, class: 'hidden main__form__image'
        = f.submit 'Send', class: 'main__form__btn'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'